version: "3.1"

services:
  db:
    restart: always
    image: dinkylink/db
    build:
      context: services/db
      dockerfile: Dockerfile
    env_file:
      - .env
    command: ["--auth"]
    ports:
      - 127.0.0.1:${DB_PORT}:${DB_PORT}
    volumes:
      - ./services/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:so
      - dinky_db_volume:/data/db
    networks:
      - dinky_net

  create:
    restart: always
    image: dinkylink/create
    build:
      context: services/create
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 127.0.0.1:${CREATE_PORT}:${CREATE_PORT}
    volumes:
      - ./services/create/lib:/usr/src/app/lib:so
    depends_on:
      - db
    networks:
      - dinky_net

  view:
    restart: always
    image: dinkylink/view
    build:
      context: services/view
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 127.0.0.1:${VIEW_PORT}:${VIEW_PORT}
    volumes:
      - ./services/view/lib:/usr/src/app/lib:so
    depends_on:
      - broker
    networks:
      - dinky_net

  stats:
    restart: always
    image: dinkylink/visit
    build:
      context: services/visit
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 127.0.0.1:${STATS_PORT}:${STATS_PORT}
    volumes:
      - ./services/stats/lib:/usr/src/app/lib:so
    depends_on:
      - broker
      - cache
      - db
      - stream
    networks:
      - dinky_net

  visit:
    restart: always
    image: dinkylink/visit
    build:
      context: services/visit
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 127.0.0.1:${VISIT_PORT}:${VISIT_PORT}
    volumes:
      - ./services/visit/lib:/usr/src/app/lib:so
    depends_on:
      - broker
      - cache
      - db
    networks:
      - dinky_net

  ui:
    restart: always
    image: dinkylink/ui
    build:
      context: services/ui
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 127.0.0.1:${UI_PORT}:${UI_PORT}
    volumes:
      - ./services/ui/dist:/usr/src/app/dist:so
    depends_on:
      - visit
      - create
      - view
    networks:
      - dinky_net

  proxy:
    restart: always
    image: nginx:1.25.2-alpine
    environment:
      - SSL_CERT=${SSL_CERT}
      - SSL_CERT_KEY=${SSL_CERT_KEY}
      - UI_HOST=${UI_HOST}
      - UI_PORT=${UI_PORT}
      - CREATE_HOST=${CREATE_HOST}
      - CREATE_PORT=${CREATE_PORT}
      - VIEW_HOST=${VIEW_HOST}
      - VIEW_PORT=${VIEW_PORT}
      - VISIT_HOST=${VISIT_HOST}
      - VISIT_PORT=${VISIT_PORT}
      - STATS_HOST=${STATS_HOST}
      - STATS_PORT=${STATS_PORT}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/proxy/templates:/etc/nginx/templates
      - ${SSL_CERT_DIRECTORY}:/etc/dinkylink/ssl:so
    depends_on:
      - create
      - view
      - visit
      - db
      - cache
      - broker
      - ui
      - stats
    networks:
      - dinky_net

  cache:
    restart: always
    image: redis:7.2.0-alpine
    env_file:
      - .env
    volumes:
      - dinky_cache_volume:/data
    depends_on:
      - db
    networks:
      - dinky_net

  broker:
    restart: always
    image: redis:7.2.0-alpine
    env_file:
      - .env
    volumes:
      - dinky_broker_volume:/data
    networks:
      - dinky_net

  stream:
    restart: always
    image: redis:7.2.0-alpine
    env_file:
      - .env
    volumes:
      - dinky_stream_volume:/data
    networks:
      - dinky_net

volumes:
  dinky_db_volume:
  dinky_cache_volume:
  dinky_broker_volume:
  dinky_stream_volume:

networks:
  dinky_net:
    driver: bridge
